=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'spec_helper'
require 'json'

# Unit tests for CyberSource::InstructionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InstructionsApi' do
  before do
    # run before each test
    @instance = CyberSource::InstructionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstructionsApi' do
    it 'should create an instance of InstructionsApi' do
      expect(@instance).to be_instance_of(CyberSource::InstructionsApi)
    end
  end

  # unit tests for cancel_purchase_intent
  # Cancel a purchase intent
  # Cancels an existing purchase intent identified by the transaction ID.
  # @param instruction_id 
  # @param agentic_cancel_purchase_intent_request Unique identifier for the purchase intent instruction.
  # @param [Hash] opts the optional parameters
  # @return [AgenticCreatePurchaseIntentResponse200]
  describe 'cancel_purchase_intent test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for confirm_transaction_events
  # Confirm transaction events
  # Agents send the confirm transaction events to notify the payment processing is done
  # @param instruction_id Unique identifier for the purchase intent instruction.
  # @param agentic_confirm_transaction_events_request 
  # @param [Hash] opts the optional parameters
  # @return [AgenticConfirmTransactionEventsResponse202]
  describe 'confirm_transaction_events test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for initiate_purchase_intent
  # Initiate a purchase intent
  # Creates a new purchase intent with the provided details.
  # @param agentic_create_purchase_intent_request 
  # @param [Hash] opts the optional parameters
  # @return [AgenticCreatePurchaseIntentResponse200]
  describe 'initiate_purchase_intent test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retrieve_payment_credentials
  # Retrieve payment credentials
  # Retrieve a customer&#39;s tokenized payment credentials to complete the transaction.
  # @param instruction_id Unique identifier for the purchase intent instruction.
  # @param agentic_retrieve_payment_credentials_request 
  # @param [Hash] opts the optional parameters
  # @return [AgenticRetrievePaymentCredentialsResponse200]
  describe 'retrieve_payment_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_purchase_intent
  # Update a purchase intent
  # Updates an existing purchase intent identified by the transaction ID.
  # @param instruction_id Unique identifier for the purchase intent instruction.
  # @param agentic_update_purchase_intent_request 
  # @param [Hash] opts the optional parameters
  # @return [AgenticCreatePurchaseIntentResponse200]
  describe 'update_purchase_intent test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
