=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'uri'
require 'AuthenticationSDK/util/MLEUtility'
module CyberSource
  class InstructionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default, config)
      @api_client = api_client
      @api_client.set_configuration(config)
    end
    # Cancel a purchase intent
    # Cancels an existing purchase intent identified by the transaction ID.
    #
    # @param instruction_id 
    # @param agentic_cancel_purchase_intent_request Unique identifier for the purchase intent instruction.
    # @param [Hash] opts the optional parameters
    # @return [AgenticCreatePurchaseIntentResponse200]
    #
    def cancel_purchase_intent(instruction_id, agentic_cancel_purchase_intent_request, opts = {})
      data, status_code, headers = cancel_purchase_intent_with_http_info(instruction_id, agentic_cancel_purchase_intent_request, opts)
      return data, status_code, headers
    end

    # Cancel a purchase intent
    # Cancels an existing purchase intent identified by the transaction ID.
    # @param instruction_id 
    # @param agentic_cancel_purchase_intent_request Unique identifier for the purchase intent instruction.
    # @param [Hash] opts the optional parameters
    # @return [Array<(AgenticCreatePurchaseIntentResponse200, Fixnum, Hash)>] AgenticCreatePurchaseIntentResponse200 data, response status code and response headers
    def cancel_purchase_intent_with_http_info(instruction_id, agentic_cancel_purchase_intent_request, opts = {})

      if @api_client.config.debugging
          begin
            raise
                @api_client.config.logger.debug 'Calling API: InstructionsApi.cancel_purchase_intent ...'
            rescue
                puts 'Cannot write to log'
            end
      end
      # verify the required parameter 'instruction_id' is set
      if @api_client.config.client_side_validation && instruction_id.nil?
        fail ArgumentError, "Missing the required parameter 'instruction_id' when calling InstructionsApi.cancel_purchase_intent"
      end
      # verify the required parameter 'agentic_cancel_purchase_intent_request' is set
      if @api_client.config.client_side_validation && agentic_cancel_purchase_intent_request.nil?
        fail ArgumentError, "Missing the required parameter 'agentic_cancel_purchase_intent_request' when calling InstructionsApi.cancel_purchase_intent"
      end
      # resource path
      local_var_path = 'acp/v1/instructions/{instructionId}/cancel'.sub('{' + 'instructionId' + '}', instruction_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/hal+json;charset=utf-8'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json;charset=utf-8'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(agentic_cancel_purchase_intent_request)
      sdk_tracker = SdkTracker.new
      post_body = sdk_tracker.insert_developer_id_tracker(post_body, 'AgenticCancelPurchaseIntentRequest', @api_client.config.host, @api_client.merchantconfig.defaultDeveloperId)
      inbound_mle_status = "mandatory"
      if MLEUtility.check_is_mle_for_API(@api_client.merchantconfig, inbound_mle_status, ["cancel_purchase_intent","cancel_purchase_intent_with_http_info"])
        begin
          post_body = MLEUtility.encrypt_request_payload(@api_client.merchantconfig, post_body)
        rescue
          raise
        end
      end

      is_response_mle_for_api = MLEUtility.check_is_response_mle_for_api(@api_client.merchantconfig, ["cancel_purchase_intent","cancel_purchase_intent_with_http_info"])

      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'AgenticCreatePurchaseIntentResponse200',
        :isResponseMLEForApi => is_response_mle_for_api)
      if @api_client.config.debugging
        begin
        raise
            @api_client.config.logger.debug "API called: InstructionsApi#cancel_purchase_intent\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
        rescue
            puts 'Cannot write to log'
        end
      end
      return data, status_code, headers
    end
    # Confirm transaction events
    # Agents send the confirm transaction events to notify the payment processing is done
    #
    # @param instruction_id Unique identifier for the purchase intent instruction.
    # @param agentic_confirm_transaction_events_request 
    # @param [Hash] opts the optional parameters
    # @return [AgenticConfirmTransactionEventsResponse202]
    #
    def confirm_transaction_events(instruction_id, agentic_confirm_transaction_events_request, opts = {})
      data, status_code, headers = confirm_transaction_events_with_http_info(instruction_id, agentic_confirm_transaction_events_request, opts)
      return data, status_code, headers
    end

    # Confirm transaction events
    # Agents send the confirm transaction events to notify the payment processing is done
    # @param instruction_id Unique identifier for the purchase intent instruction.
    # @param agentic_confirm_transaction_events_request 
    # @param [Hash] opts the optional parameters
    # @return [Array<(AgenticConfirmTransactionEventsResponse202, Fixnum, Hash)>] AgenticConfirmTransactionEventsResponse202 data, response status code and response headers
    def confirm_transaction_events_with_http_info(instruction_id, agentic_confirm_transaction_events_request, opts = {})

      if @api_client.config.debugging
          begin
            raise
                @api_client.config.logger.debug 'Calling API: InstructionsApi.confirm_transaction_events ...'
            rescue
                puts 'Cannot write to log'
            end
      end
      # verify the required parameter 'instruction_id' is set
      if @api_client.config.client_side_validation && instruction_id.nil?
        fail ArgumentError, "Missing the required parameter 'instruction_id' when calling InstructionsApi.confirm_transaction_events"
      end
      # verify the required parameter 'agentic_confirm_transaction_events_request' is set
      if @api_client.config.client_side_validation && agentic_confirm_transaction_events_request.nil?
        fail ArgumentError, "Missing the required parameter 'agentic_confirm_transaction_events_request' when calling InstructionsApi.confirm_transaction_events"
      end
      # resource path
      local_var_path = 'acp/v1/instructions/{instructionId}/confirmations'.sub('{' + 'instructionId' + '}', instruction_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/hal+json;charset=utf-8'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json;charset=utf-8'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(agentic_confirm_transaction_events_request)
      sdk_tracker = SdkTracker.new
      post_body = sdk_tracker.insert_developer_id_tracker(post_body, 'AgenticConfirmTransactionEventsRequest', @api_client.config.host, @api_client.merchantconfig.defaultDeveloperId)
      inbound_mle_status = "mandatory"
      if MLEUtility.check_is_mle_for_API(@api_client.merchantconfig, inbound_mle_status, ["confirm_transaction_events","confirm_transaction_events_with_http_info"])
        begin
          post_body = MLEUtility.encrypt_request_payload(@api_client.merchantconfig, post_body)
        rescue
          raise
        end
      end

      is_response_mle_for_api = MLEUtility.check_is_response_mle_for_api(@api_client.merchantconfig, ["confirm_transaction_events","confirm_transaction_events_with_http_info"])

      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'AgenticConfirmTransactionEventsResponse202',
        :isResponseMLEForApi => is_response_mle_for_api)
      if @api_client.config.debugging
        begin
        raise
            @api_client.config.logger.debug "API called: InstructionsApi#confirm_transaction_events\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
        rescue
            puts 'Cannot write to log'
        end
      end
      return data, status_code, headers
    end
    # Initiate a purchase intent
    # Creates a new purchase intent with the provided details.
    #
    # @param agentic_create_purchase_intent_request 
    # @param [Hash] opts the optional parameters
    # @return [AgenticCreatePurchaseIntentResponse200]
    #
    def initiate_purchase_intent(agentic_create_purchase_intent_request, opts = {})
      data, status_code, headers = initiate_purchase_intent_with_http_info(agentic_create_purchase_intent_request, opts)
      return data, status_code, headers
    end

    # Initiate a purchase intent
    # Creates a new purchase intent with the provided details.
    # @param agentic_create_purchase_intent_request 
    # @param [Hash] opts the optional parameters
    # @return [Array<(AgenticCreatePurchaseIntentResponse200, Fixnum, Hash)>] AgenticCreatePurchaseIntentResponse200 data, response status code and response headers
    def initiate_purchase_intent_with_http_info(agentic_create_purchase_intent_request, opts = {})

      if @api_client.config.debugging
          begin
            raise
                @api_client.config.logger.debug 'Calling API: InstructionsApi.initiate_purchase_intent ...'
            rescue
                puts 'Cannot write to log'
            end
      end
      # verify the required parameter 'agentic_create_purchase_intent_request' is set
      if @api_client.config.client_side_validation && agentic_create_purchase_intent_request.nil?
        fail ArgumentError, "Missing the required parameter 'agentic_create_purchase_intent_request' when calling InstructionsApi.initiate_purchase_intent"
      end
      # resource path
      local_var_path = 'acp/v1/instructions'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/hal+json;charset=utf-8'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json;charset=utf-8'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(agentic_create_purchase_intent_request)
      sdk_tracker = SdkTracker.new
      post_body = sdk_tracker.insert_developer_id_tracker(post_body, 'AgenticCreatePurchaseIntentRequest', @api_client.config.host, @api_client.merchantconfig.defaultDeveloperId)
      inbound_mle_status = "mandatory"
      if MLEUtility.check_is_mle_for_API(@api_client.merchantconfig, inbound_mle_status, ["initiate_purchase_intent","initiate_purchase_intent_with_http_info"])
        begin
          post_body = MLEUtility.encrypt_request_payload(@api_client.merchantconfig, post_body)
        rescue
          raise
        end
      end

      is_response_mle_for_api = MLEUtility.check_is_response_mle_for_api(@api_client.merchantconfig, ["initiate_purchase_intent","initiate_purchase_intent_with_http_info"])

      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'AgenticCreatePurchaseIntentResponse200',
        :isResponseMLEForApi => is_response_mle_for_api)
      if @api_client.config.debugging
        begin
        raise
            @api_client.config.logger.debug "API called: InstructionsApi#initiate_purchase_intent\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
        rescue
            puts 'Cannot write to log'
        end
      end
      return data, status_code, headers
    end
    # Retrieve payment credentials
    # Retrieve a customer's tokenized payment credentials to complete the transaction.
    #
    # @param instruction_id Unique identifier for the purchase intent instruction.
    # @param agentic_retrieve_payment_credentials_request 
    # @param [Hash] opts the optional parameters
    # @return [AgenticRetrievePaymentCredentialsResponse200]
    #
    def retrieve_payment_credentials(instruction_id, agentic_retrieve_payment_credentials_request, opts = {})
      data, status_code, headers = retrieve_payment_credentials_with_http_info(instruction_id, agentic_retrieve_payment_credentials_request, opts)
      return data, status_code, headers
    end

    # Retrieve payment credentials
    # Retrieve a customer&#39;s tokenized payment credentials to complete the transaction.
    # @param instruction_id Unique identifier for the purchase intent instruction.
    # @param agentic_retrieve_payment_credentials_request 
    # @param [Hash] opts the optional parameters
    # @return [Array<(AgenticRetrievePaymentCredentialsResponse200, Fixnum, Hash)>] AgenticRetrievePaymentCredentialsResponse200 data, response status code and response headers
    def retrieve_payment_credentials_with_http_info(instruction_id, agentic_retrieve_payment_credentials_request, opts = {})

      if @api_client.config.debugging
          begin
            raise
                @api_client.config.logger.debug 'Calling API: InstructionsApi.retrieve_payment_credentials ...'
            rescue
                puts 'Cannot write to log'
            end
      end
      # verify the required parameter 'instruction_id' is set
      if @api_client.config.client_side_validation && instruction_id.nil?
        fail ArgumentError, "Missing the required parameter 'instruction_id' when calling InstructionsApi.retrieve_payment_credentials"
      end
      # verify the required parameter 'agentic_retrieve_payment_credentials_request' is set
      if @api_client.config.client_side_validation && agentic_retrieve_payment_credentials_request.nil?
        fail ArgumentError, "Missing the required parameter 'agentic_retrieve_payment_credentials_request' when calling InstructionsApi.retrieve_payment_credentials"
      end
      # resource path
      local_var_path = 'acp/v1/instructions/{instructionId}/credentials'.sub('{' + 'instructionId' + '}', instruction_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/hal+json;charset=utf-8'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json;charset=utf-8'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(agentic_retrieve_payment_credentials_request)
      sdk_tracker = SdkTracker.new
      post_body = sdk_tracker.insert_developer_id_tracker(post_body, 'AgenticRetrievePaymentCredentialsRequest', @api_client.config.host, @api_client.merchantconfig.defaultDeveloperId)
      inbound_mle_status = "mandatory"
      if MLEUtility.check_is_mle_for_API(@api_client.merchantconfig, inbound_mle_status, ["retrieve_payment_credentials","retrieve_payment_credentials_with_http_info"])
        begin
          post_body = MLEUtility.encrypt_request_payload(@api_client.merchantconfig, post_body)
        rescue
          raise
        end
      end

      is_response_mle_for_api = MLEUtility.check_is_response_mle_for_api(@api_client.merchantconfig, ["retrieve_payment_credentials","retrieve_payment_credentials_with_http_info"])

      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'AgenticRetrievePaymentCredentialsResponse200',
        :isResponseMLEForApi => is_response_mle_for_api)
      if @api_client.config.debugging
        begin
        raise
            @api_client.config.logger.debug "API called: InstructionsApi#retrieve_payment_credentials\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
        rescue
            puts 'Cannot write to log'
        end
      end
      return data, status_code, headers
    end
    # Update a purchase intent
    # Updates an existing purchase intent identified by the transaction ID.
    #
    # @param instruction_id Unique identifier for the purchase intent instruction.
    # @param agentic_update_purchase_intent_request 
    # @param [Hash] opts the optional parameters
    # @return [AgenticCreatePurchaseIntentResponse200]
    #
    def update_purchase_intent(instruction_id, agentic_update_purchase_intent_request, opts = {})
      data, status_code, headers = update_purchase_intent_with_http_info(instruction_id, agentic_update_purchase_intent_request, opts)
      return data, status_code, headers
    end

    # Update a purchase intent
    # Updates an existing purchase intent identified by the transaction ID.
    # @param instruction_id Unique identifier for the purchase intent instruction.
    # @param agentic_update_purchase_intent_request 
    # @param [Hash] opts the optional parameters
    # @return [Array<(AgenticCreatePurchaseIntentResponse200, Fixnum, Hash)>] AgenticCreatePurchaseIntentResponse200 data, response status code and response headers
    def update_purchase_intent_with_http_info(instruction_id, agentic_update_purchase_intent_request, opts = {})

      if @api_client.config.debugging
          begin
            raise
                @api_client.config.logger.debug 'Calling API: InstructionsApi.update_purchase_intent ...'
            rescue
                puts 'Cannot write to log'
            end
      end
      # verify the required parameter 'instruction_id' is set
      if @api_client.config.client_side_validation && instruction_id.nil?
        fail ArgumentError, "Missing the required parameter 'instruction_id' when calling InstructionsApi.update_purchase_intent"
      end
      # verify the required parameter 'agentic_update_purchase_intent_request' is set
      if @api_client.config.client_side_validation && agentic_update_purchase_intent_request.nil?
        fail ArgumentError, "Missing the required parameter 'agentic_update_purchase_intent_request' when calling InstructionsApi.update_purchase_intent"
      end
      # resource path
      local_var_path = 'acp/v1/instructions/{instructionId}'.sub('{' + 'instructionId' + '}', instruction_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/hal+json;charset=utf-8'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json;charset=utf-8'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(agentic_update_purchase_intent_request)
      sdk_tracker = SdkTracker.new
      post_body = sdk_tracker.insert_developer_id_tracker(post_body, 'AgenticUpdatePurchaseIntentRequest', @api_client.config.host, @api_client.merchantconfig.defaultDeveloperId)
      inbound_mle_status = "mandatory"
      if MLEUtility.check_is_mle_for_API(@api_client.merchantconfig, inbound_mle_status, ["update_purchase_intent","update_purchase_intent_with_http_info"])
        begin
          post_body = MLEUtility.encrypt_request_payload(@api_client.merchantconfig, post_body)
        rescue
          raise
        end
      end

      is_response_mle_for_api = MLEUtility.check_is_response_mle_for_api(@api_client.merchantconfig, ["update_purchase_intent","update_purchase_intent_with_http_info"])

      auth_names = []
      data, status_code, headers = @api_client.call_api(:PUT, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'AgenticCreatePurchaseIntentResponse200',
        :isResponseMLEForApi => is_response_mle_for_api)
      if @api_client.config.debugging
        begin
        raise
            @api_client.config.logger.debug "API called: InstructionsApi#update_purchase_intent\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
        rescue
            puts 'Cannot write to log'
        end
      end
      return data, status_code, headers
    end
  end
end
