=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'uri'
require 'AuthenticationSDK/util/MLEUtility'
module CyberSource
  class OffersApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default, config)
      @api_client = api_client
      @api_client.set_configuration(config)
    end
    # Retrieve an Offer
    # Retrieves an offer record from the system. 
    #
    # @param content_type 
    # @param x_requestid 
    # @param v_c_merchant_id 
    # @param v_c_correlation_id 
    # @param v_c_organization_id 
    # @param id Request ID generated by Cybersource. This was sent in the header on the request. Echo value from v-c-request-id
    # @param [Hash] opts the optional parameters
    # @return [InlineResponse20016]
    #
    def get_offer(content_type, x_requestid, v_c_merchant_id, v_c_correlation_id, v_c_organization_id, id, opts = {})
      data, status_code, headers = get_offer_with_http_info(content_type, x_requestid, v_c_merchant_id, v_c_correlation_id, v_c_organization_id, id, opts)
      return data, status_code, headers
    end

    # Retrieve an Offer
    # Retrieves an offer record from the system. 
    # @param content_type 
    # @param x_requestid 
    # @param v_c_merchant_id 
    # @param v_c_correlation_id 
    # @param v_c_organization_id 
    # @param id Request ID generated by Cybersource. This was sent in the header on the request. Echo value from v-c-request-id
    # @param [Hash] opts the optional parameters
    # @return [Array<(InlineResponse20016, Fixnum, Hash)>] InlineResponse20016 data, response status code and response headers
    def get_offer_with_http_info(content_type, x_requestid, v_c_merchant_id, v_c_correlation_id, v_c_organization_id, id, opts = {})

      if @api_client.config.debugging
          begin
            raise
                @api_client.config.logger.debug 'Calling API: OffersApi.get_offer ...'
            rescue
                puts 'Cannot write to log'
            end
      end
      # verify the required parameter 'content_type' is set
      if @api_client.config.client_side_validation && content_type.nil?
        fail ArgumentError, "Missing the required parameter 'content_type' when calling OffersApi.get_offer"
      end
      # verify the required parameter 'x_requestid' is set
      if @api_client.config.client_side_validation && x_requestid.nil?
        fail ArgumentError, "Missing the required parameter 'x_requestid' when calling OffersApi.get_offer"
      end
      # verify the required parameter 'v_c_merchant_id' is set
      if @api_client.config.client_side_validation && v_c_merchant_id.nil?
        fail ArgumentError, "Missing the required parameter 'v_c_merchant_id' when calling OffersApi.get_offer"
      end
      # verify the required parameter 'v_c_correlation_id' is set
      if @api_client.config.client_side_validation && v_c_correlation_id.nil?
        fail ArgumentError, "Missing the required parameter 'v_c_correlation_id' when calling OffersApi.get_offer"
      end
      # verify the required parameter 'v_c_organization_id' is set
      if @api_client.config.client_side_validation && v_c_organization_id.nil?
        fail ArgumentError, "Missing the required parameter 'v_c_organization_id' when calling OffersApi.get_offer"
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling OffersApi.get_offer"
      end
      # resource path
      local_var_path = 'vas/v1/currencyconversion/{id}'.sub('{' + 'id' + '}', id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/hal+json;charset=utf-8'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json;charset=utf-8'])
      header_params[:'Content-Type'] = content_type
      header_params[:'x-requestid'] = x_requestid
      header_params[:'v-c-merchant-id'] = v_c_merchant_id
      header_params[:'v-c-correlation-id'] = v_c_correlation_id
      header_params[:'v-c-organization-id'] = v_c_organization_id

      # form parameters
      form_params = {}

      # http body (model)
      if 'GET' == 'POST'
        post_body = '{}'
      else
        post_body = nil
      end
      inbound_mle_status = "false"
      if MLEUtility.check_is_mle_for_API(@api_client.merchantconfig, inbound_mle_status, ["get_offer","get_offer_with_http_info"])
        begin
          post_body = MLEUtility.encrypt_request_payload(@api_client.merchantconfig, post_body)
        rescue
          raise
        end
      end

      is_response_mle_for_api = MLEUtility.check_is_response_mle_for_api(@api_client.merchantconfig, ["get_offer","get_offer_with_http_info"])

      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse20016',
        :isResponseMLEForApi => is_response_mle_for_api)
      if @api_client.config.debugging
        begin
        raise
            @api_client.config.logger.debug "API called: OffersApi#get_offer\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
        rescue
            puts 'Cannot write to log'
        end
      end
      return data, status_code, headers
    end
  end
end
